JAVAC = javac
JAVA = java
SOURCE = gatorLibrary.java
TARGET = gatorLibrary.class

default: $(TARGET)

$(TARGET): $(SOURCE)
	$(JAVAC) $(SOURCE)

run1: $(TARGET)
	$(JAVA) gatorLibrary inputFile1.txt

run2: $(TARGET)
	$(JAVA) gatorLibrary inputFile2.txt

run3: $(TARGET)
	$(JAVA) gatorLibrary inputFile3.txt

run4: $(TARGET)
	$(JAVA) gatorLibrary inputFile4.txt

run5: $(TARGET)
	$(JAVA) gatorLibrary inputFile5.txt

run6: $(TARGET)
	$(JAVA) gatorLibrary inputFile6.txt

run7: $(TARGET)
	$(JAVA) gatorLibrary inputFile7.txt

clean:
	rm -f *.class